#!/usr/bin/env python3
"""
Generate the planned physical master copy manifest.

READ-ONLY with respect to source files:
- does not copy
- does not move
- does not delete
- does not rename

It creates/refreshes PLANNED rows in SQLite copy_manifest for files that
are currently selected for the master.
"""

import argparse
import sqlite3
from pathlib import Path


def master_selection_sql():
    return """
    SELECT
        f.file_id,
        f.filename,
        f.extension,
        f.size_bytes,
        f.sha256,
        fs.device_id AS source_device_id,
        fs.source_path,
        CASE
            WHEN dg.duplicate_group_id IS NULL THEN 1
            WHEN dg.chosen_file_id = f.file_id THEN 1
            ELSE 0
        END AS master_action
    FROM files f
    JOIN file_sources fs
        ON fs.file_id = f.file_id
    LEFT JOIN duplicate_members dm
        ON dm.file_id = f.file_id
    LEFT JOIN duplicate_groups dg
        ON dg.duplicate_group_id = dm.duplicate_group_id
    WHERE
        dg.duplicate_group_id IS NULL
        OR dg.chosen_file_id = f.file_id
    ORDER BY f.file_id;
    """


def safe_destination(master_root: Path, source_path: str, source_roots):
    """
    Preserve the selected source-relative path in the first-pass master.

    source_roots is a list of (device_id, root_path) tuples. The source path
    from the catalog is expected to be inside one of these roots.

    Destination:
        MASTER_ROOT / device_id / relative-source-path

    Using the device ID in the destination prevents accidental collisions
    while we are still preserving source structure. This is a planning choice;
    later organization can flatten/merge paths.
    """
    src = Path(source_path).expanduser().resolve()

    for device_id, root in source_roots:
        root = Path(root).expanduser().resolve()
        try:
            rel = src.relative_to(root)
        except ValueError:
            continue

        if ".." in rel.parts:
            continue

        return Path(device_id) / rel

    raise ValueError(
        f"Source path is not under any configured source root: {source_path}"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--db",
        default=str(Path.home() / "Master-Repository/.archive/catalog.db"),
    )
    parser.add_argument(
        "--master-root",
        default=str(Path.home() / "Master-Repository"),
    )
    parser.add_argument(
        "--source-root",
        action="append",
        nargs=2,
        metavar=("DEVICE_ID", "ROOT"),
        required=True,
        help="Repeat for each source device, e.g. TABLET /path and PC /path",
    )
    args = parser.parse_args()

    db = Path(args.db).expanduser().resolve()
    master_root = Path(args.master_root).expanduser().resolve()

    if not db.is_file():
        raise SystemExit(f"ERROR: database does not exist: {db}")

    source_roots = [
        (device.upper(), Path(root).expanduser().resolve())
        for device, root in args.source_root
    ]

    con = sqlite3.connect(db)
    con.execute("PRAGMA foreign_keys = ON")

    rows = con.execute(master_selection_sql()).fetchall()

    # We regenerate only PLANNED rows. Existing COPIED/VERIFIED/FAILED rows
    # are left untouched to preserve audit history.
    con.execute("DELETE FROM copy_manifest WHERE status='PLANNED'")

    planned = 0
    skipped = 0
    errors = []

    for (
        file_id,
        filename,
        extension,
        size_bytes,
        sha256,
        source_device_id,
        source_path,
        master_action,
    ) in rows:
        if not master_action:
            skipped += 1
            continue

        try:
            rel_destination = safe_destination(
                master_root,
                source_path,
                source_roots,
            )
            destination = master_root / rel_destination
        except ValueError as exc:
            errors.append(str(exc))
            continue

        con.execute(
            """
            INSERT INTO copy_manifest (
                file_id,
                source_device_id,
                source_path,
                destination_path,
                source_sha256,
                source_size_bytes,
                status,
                notes
            )
            VALUES (?, ?, ?, ?, ?, ?, 'PLANNED', ?)
            """,
            (
                file_id,
                source_device_id,
                source_path,
                str(destination),
                sha256,
                size_bytes,
                "Generated by plan_master_copy.py; no file operation performed.",
            ),
        )
        planned += 1

    con.commit()

    summary = {
        "catalog_master_candidates": len(rows),
        "planned": planned,
        "skipped": skipped,
        "errors": len(errors),
        "planned_db_count": con.execute(
            "SELECT COUNT(*) FROM copy_manifest WHERE status='PLANNED'"
        ).fetchone()[0],
    }

    print("MODE                  : PLAN ONLY")
    print("Database              :", db)
    print("Master root           :", master_root)
    print()
    for key, value in summary.items():
        print(f"{key:24}: {value}")

    if errors:
        print("\nERRORS:")
        for error in errors:
            print(" -", error)
        con.close()
        raise SystemExit(
            "Manifest generation completed with errors. "
            "No physical files were copied."
        )

    print(
        "\nNo source files were copied, moved, deleted, renamed, or modified."
    )
    print(
        "Review the PLANNED rows in Beekeeper Studio before the copy stage."
    )

    con.close()


if __name__ == "__main__":
    main()
