-- ============================================================
-- Digital Archive catalog migration: canonical path + storage state
-- Safe/idempotent for the current SQLite catalog.
-- ============================================================

-- Add canonical_path once. SQLite has no IF NOT EXISTS for ADD COLUMN,
-- so run the Python migration script rather than this file directly if
-- the column may already exist.

-- The following logical fields are added:
--
-- files.canonical_path
--     The intended final repository path.
--
-- files.storage_state
--     IN_MASTER         = physically present in Master-Repository
--     MOVED_EXTERNAL    = intentionally moved out to another storage device
--     IN_BIN            = moved to archive/deletion bin
--     MISSING           = expected but not currently found
--
-- files.external_device_id
--     Device holding the file when storage_state=MOVED_EXTERNAL.
--
-- files.external_path
--     Path on that external storage.
--
-- files.moved_out_at
--     Timestamp of the physical move out of Master-Repository.
--
-- files.storage_move_reason
--     Why it was moved.
--
-- The database remains authoritative; no filesystem changes are made by
-- this migration.
